spring:
  application:
    name: consumer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
server:
  port: 8080
    
